---

port: 4000
host: 0.0.0.0
safe: false

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments

### content configuration ###
title:       "trevanhaskell.com"
keywords:    "music, jekyll, videos, github, blog, single page"
description: "A place for me to share"
favicon:     "img/favicon.ico"
touch_icon:  "img/touch-icon.png"

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#4B306A'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
	red:       '#F93738'

kramdown:
  auto_ids:  false

