# Site settings
title: trevanhaskell.com
email: trevan.haskell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Built with Jekyll and hosted with Github Pages
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://trevanhaskell.com" # the base hostname & protocol for your site
github_username:  tjhaskel

# Build settings
markdown: kramdown
